
version: '1'

services:
  jenkins:
    build:
      context: .
      dockerfile: './Dockerfile'
    container_name: jenkins_container
    ports: 
    - 8081:8080
    - 50000:50000
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - JENKINS_OPTS="--prefix=/cicdeasydata"
      - JENKINS_UID=${JENKINS_UID}
      - JENKINS_GID=${JENKINS_GID}
    mem_limit: 1500m
